### ISSUE TITLE
Unit Testing - Navigation Flows

### ISSUE THREAD

**Issue by Gdev82** [dcutting/Remix#2]
Hi Dan, 
I know this is an old repo, and I am not sure if is maintained, but we are trying to see if we can incorporate some of the aspects into our project, and I have the following question about testing navigation flows.

When writing a unit test about the coordinator that performs an async call via the interactor that after completion pushes a new view onto the stack. How is it possible to check that the top view is pushed correctly? 

Following is an example:

```
class CoordinatorA {
    struct Dependencies {
        let viewFactoryA: ViewFactoryA
        let navigationStack: NavigationWireframe
        let interactor: InteractorA
        let formatter: FormatterA
        let featureB: FeatureB
    }
    
    let deps: Dependencies
    private var view: ViewA?
    private var coordinatorB: CoordinatorB?
    
    
    init(dependencies: Dependencies) {
        self.deps = dependencies
    }

    func start() {
        showA()
    }
}

extension CoordinatorA: ViewADelegate {
    
    func showA() {
        let view = deps.viewFactoryA.make()
        self.view = view
        self.view?.delegate = self
        deps.navigationStack.push(view: view)
    }
    
    func viewDidTapB() {
        self.deps.interactor.doAsyncSomething().done { data in
            self.handleResponse(with: data)
        }.ensure {
            
        }.catch { error in
        }
    }
    
    private func handleResponse(with data: data) {
        let coordinatorB = self.deps.featureB.makeCoordinatorB(navigationStack: self.deps.navigationStack)
        coordinatorB.start()
        self.coordinatorB = coordinatorB
    }
} 
```

How can you write a unit test for this coordinator and check that when ```viewDidTapB``` is called and after the interaction (mocked for testing) the view from featureB is pushed correctly in the navigation stack? Since the call to ```self.deps.interactor.doAsyncSomething``` is async and does not wait for the response to come back.

If you can give me some pointers it would be greatly appreciated.

Thank you in advance.

George

**Comment by Gdev82** [comment]
Dear Dan,

I finally figured it out. I was using promisekit, and I had to put this 
```// in your test suite setup code
PromiseKit.conf.Q.map = nil
PromiseKit.conf.Q.return = nil
```
in my code in order for the promises to run all on the main thread

Thank you

**Comment by dcutting** [comment]
Hi George, sorry for not getting back to you earlier.

I don't have experience with PromiseKit, but I suppose by putting everything on the main thread you ensure that your test blocks until the view is pushed so you can test it synchronously? Anyway, glad you sorted it out! I'm still using variations on this pattern years later and happy you find Remix useful too.

Dan
